version: '3.8'

services:
  front-sag-ribamar:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production